### ISSUE TITLE
Segmentation fault (core dumped) running 1_the_very_basic

### ISSUE THREAD

**Issue by alecomunian** [randlab/ArchPy#1]
Hi Ludovic,
when I try to run the "1_the_very_basic" notebook, I first found a RuntimeWarning and then a "segmentation fault".

The "RuntimeWarning" is due to an "invalid value encountered in long_scalars" in base.py, around line 4169
`p=np.sum(facies == fa.ID)/len(facies == fa.ID)`
There I tried to print out the value of `facies`, and it seems to be an empty list. However, the units defined in the code contain correctly the definition of some facies.
I suppose this is probably due to the fact that `facies` is initialized from data coming from the "hard data", and in the case those are missing... then the problem arises.

If I continue to execute the script after this warning, then I get a "Segmentation fault (code dumped)".
However, I also tried the 2nd example (the one with conditioning data, "2_Hard_data"), and that works fine.

Therefore, I think this could be a bug in the "1_the_very_basic" notebook, probably due to the missing hard data.

Hope this helps,
Bests,

Alessandro

**Comment by LudovicSchorpp** [comment]
Hi Alessandro, thanks for this issue. Indeed, this is a little warning that I didn't pay much attention to because everything was running properly for me but I will fix this and update the code as soon as possible.

edit : I push a new version on pip and github, normally it should work now.

Thanks again for pointing this !

Ludovic

**Comment by alecomunian** [comment]
Hi Ludovic,
thank you for the quick reply. Unfortunately, I downloaded the latest version of the code but, although the "RuntimeWarning" is now solved, there is another message "Aborted (core dumped)"... hereinafter the last lines of the script stdout when run from the shell:
`...`
`### 40 K property models will be modeled ###`
`realloc(): invalid next size`
`Aborted (core dumped)`

When run from the "cell by cell" with Spyder (or Jupyter), then the kerned dies after running line 
`T1.compute_prop(1)`.

More info: I'm running that on Python3.9.7 on Ubuntu20.04 LTS.

Bests,

Alessandro

**Comment by LudovicSchorpp** [comment]
Hi, that sounds to be an issue on linux distributions but as I run my code on windows I wasn't aware of them. I will try in the next days to make some tests on Linux and try to find the issues.

Thank you again for pointing this problem.

My best regards,
Ludovic

Edit : 
I tried to run the notebook with the same setup (python 3.9.7 and ubuntu 20.04 on a wsl) and for me all the cells run perfectly except the last ones for the vizualization which I suppose is another issue due to pyvista directly. So for the moment I don't have any clue why it is not working for you Alessandro but I keep this in mind and I will let you know.

**Comment by alecomunian** [comment]
Hi Ludovic, thank you for checking this. In the end, the issue was solved with the new version of ``geone`` and ``ArchPy``.
Bests,
