### ISSUE TITLE
Inconsistent cells when using geological map to build surfaces

### ISSUE THREAD

**Issue by dzamrsky** [randlab/ArchPy#23]
Hi,

I am trying to build a geological model consisting of multiple units (approx. 10-15) using borehole data as well as a geological map to delineate outcropping areas. It all works fine for some cases but sometimes i run into this error:

ERROR (simulate2D): 6 grid cell(s) have inconsistent "inequality min" and "inequality max" data

Is there a way how to identify and get rid of the cells where this inconsistency occurs? It usually happens when i try to use the following setup 

T1.process_geological_map(typ = "all", step = 1)

If  I increase the step to a larger number (5) the error doesnt happen. But i would still like to use as low step as possible to have an accurate representation of the outcropping areas. Is there a way how to get rid of these cells with inconsistencies?

Thanks! And really great library btw! 

Cheers, Daniel

**Comment by LudovicSchorpp** [comment]
Hi Daniel,

Thank you for pointing this out. Like this I don't know exactly what happened, but likely that something went wrong with the processing of the boreholes. Would you be able to identify for which unit this error occurs and then inspect the processed data using 
``T1.get_unit("unit_name_of_interest").surface.ineq``

This will return a list where each element is an inequality data and that takes this form: [x, y, z, 0, ineq_inf, ineq_sup]
ineq_inf and ineq_sup can be NaN.

It is then necessary to check two things:
- that for each inequality data, ineq_inf is always lower than ineq_sup (this is unlikely to happen, but let's check it anyway)
- that two (or more) inequality data points are not in the same cell (normally ArchPy checks this, but I cannot guarantee that this will never happen. And if it does, that the data with an ineq_inf is lower than the data with an ineq_sup.

If you are able to identify these things, you should be able to retrieve the boreholes that the data came from and identify the reason for these errors

If you want I can look at the problem myself if you send me your ArchPy model (notebook with borehole data file and geological map).

Oh, and also, I normally do not use step=1 or too low, because what it does is create fake small boreholes on elevation surfaces. And if you use step=1, you end up with a tiny hole in every cell of your model, which slows down the ArchPy unit simulation considerably. It is a bit of a compromise.

Cheers ! 
Ludovic

**Comment by dzamrsky** [comment]
Hi Ludovic,

thanks a lot for a quick reply! I checked both that vmin is always lower than vmax and that there is only one inequality data point in each cell and i still get the error while computing the surfaces. Although this only happens when the step = 1 so it is not really a big deal since I can just increase the step and it works well.

Thanks again for your help! Once i finalize the project and code i will send it over so you can have a look at it if you are interested.

Cheers, Daniel

**Comment by LudovicSchorpp** [comment]
That would be great in order to see what's going wrong. And do not hesitate if you have other questions or problems :)
